# build container
FROM node:alpine

RUN apk --no-cache add \
    g++ \
    make \
    python3

WORKDIR /usr/src/maw-photos
COPY "package*.json" .

ENV NG_CLI_ANALYTICS=off
RUN npm install

COPY . .

RUN npm run test_build


# dev container
FROM nginx:alpine

WORKDIR /srv/www/maw-photos

RUN rm /etc/nginx/conf.d/*

COPY etc/nginx/tls.conf                    /etc/nginx
COPY etc/nginx/test.nginx.conf             /etc/nginx/nginx.conf
COPY etc/nginx/h5bp                        /etc/nginx/h5bp
COPY etc/nginx/conf.d/test.maw-photos.conf /etc/nginx/conf.d/maw-photos.conf
COPY --from=0                              /usr/src/maw-photos/dist .

CMD [ "nginx", "-g", "daemon off;" ]
EXPOSE 4200
