# build container
FROM node:alpine

RUN apk --no-cache add \
    g++ \
    make \
    python3

WORKDIR /usr/src/maw-photos
COPY "package*.json" .

ENV NG_CLI_ANALYTICS=ci
RUN npm install

COPY . .

RUN npm run dev_build


# dev container
FROM nginx:alpine

WORKDIR /srv/www/maw-photos

COPY etc/nginx/h5bp /etc/nginx/h5bp
COPY etc/nginx/dev.nginx.conf /etc/nginx/nginx.conf
COPY etc/nginx/conf.d/dev.maw-photos.conf /etc/nginx/conf.d/maw-photos.conf
COPY --from=0 /usr/src/maw-photos/dist .

CMD [ "nginx", "-g", "daemon off;" ]
EXPOSE 80
